export default {
  disabled: false,
  error: null,
  isValid: false,
  isFetching: false,
  configurations: null,
  current: {
    name: '',
    amountPerPage: null,
    email: '',
    description: '',
    from: null,
    delta: null,
    amount: null,
    maintenance: false,
    user: null,
  },
  fields: {
    name: '',
    nameHasError: false,
    nameErrorMsg: '',
    amountPerPage: null,
    amountPerPageHasError: false,
    amountPerPageErrorMsg: '',
    email: '',
    emailHasError: false,
    emailErrorMsg: '',
    description: '',
    descriptionHasError: false,
    descriptionErrorMsg: '',
    from: null,
    fromHasError: false,
    fromErrorMsg: '',
    delta: null,
    deltaHasError: false,
    deltaErrorMsg: '',
    amount: null,
    amountHasError: false,
    amountErrorMsg: '',
    maintenance: false,
    maintenanceHasError: false,
    maintenanceErrorMsg: '',
  },
};
