export default {
  originalProfile: {
    username: null,
    email: null,
    firstName: null,
    lastName: null,
    password: null,
    active: null,
    createdAt: null,
    updatedAt: null,
    roles: null,
  },
  disabled: false,
  error: null,
  isValid: false,
  isFetching: false,
  fields: {
    username: null,
    usernameHasError: false,
    usernameErrorMsg: '',
    email: null,
    emailHasError: false,
    emailErrorMsg: '',
    password: null,
    passwordHasError: false,
    passwordErrorMsg: '',
    firstName: null,
    firstNameHasError: false,
    firstNameErrorMsg: '',
    lastName: null,
    lastNameHasError: false,
    lastNameErrorMsg: '',
  },
};
