export default {
  originalProfile: {
    username: '',
    email: '',
    firstName: '',
    lastName: '',
    password: '',
    active: null,
    createdAt: null,
    updatedAt: null,
    roles: null,
  },
  disabled: false,
  error: null,
  isValid: false,
  isFetching: false,
  fields: {
    username: '',
    usernameHasError: false,
    usernameErrorMsg: '',
    email: '',
    emailHasError: false,
    emailErrorMsg: '',
    password: '',
    passwordHasError: false,
    passwordErrorMsg: '',
    firstName: '',
    firstNameHasError: false,
    firstNameErrorMsg: '',
    lastName: '',
    lastNameHasError: false,
    lastNameErrorMsg: '',
  },
};
